#!/bin/bash

set -o errexit

DEFAULT_PROJECT=new_java_project
DEFAULT_PACKAGE_START=org.grumpyf0x48

project=${PROJECT:-${DEFAULT_PROJECT}}
package=${PACKAGE:-${DEFAULT_PACKAGE_START}.${project}}

mkdir "$project"
cd "$project"

gradle init \
    --dsl kotlin \
    --package "${package}" \
    --project-name "${project}" \
    --test-framework junit-jupiter \
    --type java-application

mv app/* .
rm -fr app
sed --in-place '$d' settings.gradle.kts
