#!/bin/bash

set -o errexit

project=${1}
package=${2:-${project}}

mkdir "$project"
cd "$project"

gradle init \
	--dsl groovy \
	--package org.grumpyf0x48."${package}" \
	--project-name "${project}" \
	--test-framework junit-jupiter \
	--type java-application

ls app
mv app/* .
rm -fr app
sed --in-place '$d' settings.gradle
