#!/bin/bash

set -o errexit

if [ "$(id -u)" -ne 0 ]; then
    echo "This script should be run as root !" >&2
    exit 1
fi

destination_folder=/usr/lib/jvms
if [ ! -d "${destination_folder}" ]; then
    mkdir ${destination_folder}
fi

source /home/${SUDO_USER}/.config/liar/liar-software
liar_options="-r -d ${destination_folder}"

liar ${liar_options} -f remove jdk_ea_23 || true
liar ${liar_options} install jdk_ea_23 ${jdk_ea_23}
ln -s -f ${destination_folder}/jdk_ea_23/jdk-23 /usr/lib/jvm/jdk23
