#!/bin/bash

set -o errexit

source ~/.config/liar/liar-software

destination_folder=~/JvmLanguages

rm -fr ${destination_folder}
mkdir ${destination_folder}

LIAR_DEFAULT_ARGS="-v -d ${destination_folder}" liar <<EOF
install groovy ${groovy}
install kotlin ${kotlin}
install scala_cli ${scala_cli}
EOF
