#!/bin/bash

#
# jbang_create_dev_env
#
# Installs a dev env for JBang.
#

set -o errexit

if [ $# -lt 1 ]; then
    echo "Usage: $0 <JBang repository> <bin dir>" 2>&1
    exit 1
fi

jbang_repo="$(realpath "$1")"
bin_dir=${2:-${HOME}/bin}

if [ ! -d "${jbang_repo}"/.git ] || [ ! -f "${jbang_repo}"/.git/config ]; then
    echo "${jbang_repo} is not a git repository" 2>&1
    exit 1
fi

url=$(grep url "${jbang_repo}"/.git/config)

if [[ ! ${url} == *jbang.git ]]; then
    echo "${jbang_repo} is not a JBang repository" 2>&1
    exit 1
fi

if [ -d ~/Programs/jbang_dev/ ]; then
    liar -f remove jbang_dev
fi

jbang_path=~/Programs/jbang_dev/jbang

liar -s "${bin_dir}" install jbang_dev "${jbang_repo}"/build/distributions/jbang.zip
ln -vsf "${jbang_repo}"/build/libs/jbang.jar ${jbang_path}/bin/jbang.jar

cat <<EOF | tee -a "${HOME}/.bashrc" >/dev/null

#
# Sets jbang 'dev' in \$PATH
#
export PATH=${jbang_path}/bin:\${PATH}
EOF

exec bash
