#!/bin/bash

set -o errexit

if [ $# -lt 1 ]; then
    echo "Usage: $0 <JBang repository> <bin dir>" 2>&1
    exit 1
fi

jbang_repo="$1"
bin_dir=${2:-${HOME}/bin}

if [ ! -d ${jbang_repo}/.git ] || [ ! -f ${jbang_repo}/.git/config ]; then
    echo "${jbang_repo} is not a git repository" 2>&1
    exit 1
fi

url=$(grep url ${jbang_repo}/.git/config)

if [[ ! ${url} == *jbang.git ]]; then
    echo "${jbang_repo} is not a JBang repository" 2>&1
    exit 1
fi

if [ -d ~/Programs/jbang_dev/ ]; then
    liar -f remove jbang_dev
fi

liar install jbang_dev ${jbang_repo}/build/distributions/jbang.zip
ln -vsf ${jbang_repo}/build/libs/jbang.jar ~/Programs/jbang_dev/jbang/bin/jbang.jar
ln -vsf ~/Programs/jbang_dev/jbang/bin/jbang ${bin_dir}/jbang_dev
