#!/bin/bash

URL=https://raw.githubusercontent.com/gradle/gradle-completion/master/gradle-completion.bash
FILE_NAME=$(basename $URL)
FILE_PATH=/tmp/${FILE_NAME}

curl -L ${URL} -o "${FILE_NAME}"
sudo cp "${FILE_PATH}" /etc/bash_completion.d/
sudo chmod a+r "/etc/bash_completion.d/${FILE_NAME}"
