#!/bin/bash

bootVersionDefault=4.0.2
javaVersionDefault=25

nameDefault=demo
groupIdDefault=org.grumpyf0x48
artifactIdDefault=demo
dependenciesDefault=web

read -p "Project spring boot version (${bootVersionDefault}): " bootVersion
read -p "Java version (${javaVersionDefault}): " javaVersion

read -p "Project name (${nameDefault}): " name
name=${name:-${nameDefault}}

read -p "Project groupId (${groupIdDefault}): " groupId
groupId=${groupId:-${groupIdDefault}}

read -p "Project artifactId (${artifactIdDefault}): " artifactId
artifactId="${artifactId:-${artifactIdDefault}}"

packageDefault=${artifactId}
read -p "Project package (${packageDefault}): " package
package="${package:-${packageDefault}}"

read -p "Project dependencies (${dependenciesDefault}): " dependencies
dependencies="${dependencies:-${dependenciesDefault}}"

folder="$(mktemp -p /tmp -d ${artifactId}.XXXX)/"

spring init \
    --build=maven \
    --boot-version="${bootVersion:-${bootVersionDefault}}" \
    --java-version="${javaVersion:-${javaVersionDefault}}" \
    --group-id="${groupId}" \
    --artifact-id="${artifactId}" \
    --package-name="${groupId}.${package}" \
    --name="${name}" \
    --type=maven-project \
    --dependencies="${dependencies}" \
    ${folder}

cd "${folder}"
./mvnw test

rm -f "${folder}/HELP.md" "${folder}/mvnw.bat"
